version: "3.8"
services:
  bge:
    build: .
    image: bge-embedding-project
    volumes:
      - ./embeddings:/app/embeddings
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: ["/bin/bash"] 